### ISSUE TITLE
Uploading Kibana objects does not work for newly deployed clusters

### ISSUE THREAD

**Issue by axelaris** [cloudfoundry-community/logsearch-for-cloudfoundry#320]
The issue is related to recently added [script](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/develop/jobs/upload-kibana-objects/templates/bin/import-objects) for uploading Kibana objects by Kibana's own API.
The error is:
```
Stderr     Traceback (most recent call last):  
             File "/var/vcap/jobs/upload-kibana-objects/bin/import-objects", line 25, in <module>  
               assert login.url == 'https://logs.{}/'.format(os.environ['CF_SYSTEM_DOMAIN'])  
           AssertionError  
```
But when I login to Kibana in a browser at least once - scripts starts working. I believe the issue is related to authorization to **kibana_oauth2_client** which can be done in a browser, but not being performed by the script.

**Comment by peterellisjones** [comment]
We're getting the same error. It works fine if we comment out the [assertion](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/develop/jobs/upload-kibana-objects/templates/bin/import-objects#L14). This is because we are using Cloud Foundry as an oauth provider so login url is 

```
https://login.<system domain>/oauth/authorize?lient_id=kibana_oauth2_client&response_type=code&redirect_uri=https%3A%2F%2F<logs domain>%2Flogin&state=<state>&scope=openid%20oauth.approvals%20scim.userids%20cloud_controller.read
```

and not 

```
https://logs.<system domain>
```

As the assertion expects
